import React from "react";
import Head from "next/head";
const PrivacyPolicyM = () => {
  return (
    <div className="bg-white">
      <Head>
        <title>Event Buddy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/appicon.png" />
      </Head>
      <div
        style={{
          marginTop: "10%",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "space-around",

          height: "40vh",
        }}
      >
        <h1 className="font-bold font-lgstrong md:font-normall text-[#E9813B] text-[34px] leading-10 md:text-4xl sm:text-center px-2">
          Privacy Policy
        </h1>
        <div className="p-5 mt-4 " style={{ width: "50vw" }}>
          <h1 className="text-lg font-mediumm text-[#E9813B]">Terms For Use</h1>
          <p className="text-sm text-[#42526E] opacity-70 mt-2">
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ratione
            iusto nobis mollitia, animi explicabo debitis modi ipsum dolorem
            velit dicta. Lorem ipsum dolor sit amet consectetur adipisicing elit
            Lorem ipsum dolor sit.
          </p>
          <h1 className="text-lg font-mediumm text-[#E9813B] mt-8">
            Request Accepting/Rejecting
          </h1>
          <p className="text-sm text-[#42526E] opacity-70 mt-2">
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ratione
            iusto nobis mollitia, animi explicabo debitis modi ipsum dolorem
            velit dicta. Lorem ipsum dolor sit amet consectetur adipisicing elit
            Lorem ipsum dolor sit.
          </p>
        </div>
        {/* <div
          style={{
            width: "60vw",
            alignSelf: "center",
          }}
        >
          <p style={{ textAlign: "justify" }}>
            Lorem Ipsum is simply dummy text of the printing and typesetting
            industry. Lorem Ipsum has been the industry's standard dummy text
            ever since the 1500s, when an unknown printer took a galley of type
            and scrambled it to make a type specimen book. It has survived not
            only five centuries, but also the leap into electronic typesetting,
            remaining essentially unchanged. It was popularised in the 1960s
            with the release of Letraset sheets containing Lorem Ipsum passages,
            and more recently with desktop publishing software like Aldus
            PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply
            dummy text of the printing and typesetting industry. Lorem Ipsum has
            been the industry's standard dummy text ever since the 1500s, when
            an unknown printer took a galley of type and scrambled it to make a
            type specimen book. It has survived not only five centuries, but
            also the leap into electronic typesetting, remaining essentially
            unchanged. It was popularised in the 1960s with the release of
            Letraset sheets containing Lorem Ipsum passages, and more recently
            with desktop publishing software like Aldus PageMaker including
            versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the
            printing and typesetting industry. Lorem Ipsum has been the
            industry's standard dummy text ever since the 1500s, when an unknown
            printer took a galley of type and scrambled it to make a type
            specimen book. It has survived not only five centuries, but also the
            leap into electronic typesetting, remaining essentially unchanged.
            It was popularised in the 1960s with the release of Letraset sheets
            containing Lorem Ipsum passages, and more recently with desktop
            publishing software like Aldus PageMaker including versions of Lorem
            Ipsum.
          </p>
        </div> */}
      </div>
    </div>
  );
};

export default PrivacyPolicyM;
