import React, { useEffect, useState } from "react";
import Head from "next/head";

const TermnConditionM = () => {
  return (
    <div className="bg-white">
      <Head>
        <title>Event Buddy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/appicon.png" />
      </Head>

      <div
        style={{
          marginTop: "7%",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "space-around",

          height: "50vh",
        }}
      >
        <h1 className="font-bold font-lgstrong md:font-normall text-[#E9813B] text-[34px] leading-10 md:text-4xl sm:text-center px-2">
          Terms & Condition
        </h1>
        <div
          style={{
            width: "60vw",
            alignSelf: "center",
          }}
        >
          <p
            style={{ textAlign: "justify" }}
            className="text-sm text-[#42526E] opacity-70 mt-2"
          >
            Lorem Ipsum is simply dummy text of the printing and typesetting
            industry. Lorem Ipsum has been the industrys standard dummy text
            ever since the 1500s, when an unknown printer took a galley of type
            and scrambled it to make a type specimen book. It has survived not
            only five centuries, but also the leap into electronic typesetting,
            remaining essentially unchanged. It was popularised in the 1960s
            with the release of Letraset sheets containing Lorem Ipsum passages,
            and more recently with desktop publishing software like Aldus
            PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply
            dummy text of the printing and typesetting industry. Lorem Ipsum has
            been the industrys standard dummy text ever since the 1500s, when an
            unknown printer took a galley of type and scrambled it to make a
            type specimen book. It has survived not only five centuries, but
            also the leap into electronic typesetting, remaining essentially
            unchanged. It was popularised in the 1960s with the release of
            Letraset sheets containing Lorem Ipsum passages, and more recently
            with desktop publishing software like Aldus PageMaker including
            versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the
            printing and typesetting industry. Lorem Ipsum has been the
            industrys standard dummy text ever since the 1500s, when an unknown
            printer took a galley of type and scrambled it to make a type
            specimen book. It has survived not only five centuries, but also the
            leap into electronic typesetting, remaining essentially unchanged.
            It was popularised in the 1960s with the release of Letraset sheets
            containing Lorem Ipsum passages, and more recently with desktop
            publishing software like Aldus PageMaker including versions of Lorem
            Ipsum.
          </p>
        </div>
      </div>
      {/* <ToastContainer />
      <Loader /> */}
    </div>
  );
};

export default TermnConditionM;
